vim.cmd([[set number]])

require("keymaps")
require("plugins")
require("colorscheme")
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.nvim-treesitter")
require("plugin-config.mason")
require("plugin-config.rust-tools")